language: node_js

notifications:
  email: false

branches:
  only:
    - frontend
    - backend
    - cryptor
    - builder
    - auth

node_js:
  - 9

script:
  - yarn test
  - yarn build

after_success:
  - yarn coveralls
  - yarn deploy

cache:
  yarn: true
  directories:
    - node_modules
