language: node_js

notifications:
  email: false

branches:
  only:
    - frontend
    - backend
    - cryptor
    - builder
    - auth

node_js:
  - 8

services:
  - mongodb

sudo: required

before_install:
  - docker --version || true
  - curl -fsSL https://get.docker.com/ | sudo bash
  - docker --version

script:
  - yarn test
  - yarn build
  - docker build -t b1f6c1c4/ballot-backend .

after_success:
  - yarn coveralls
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push b1f6c1c4/ballot-backend

cache:
  yarn: true
  directories:
    - node_modules
