apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: NAMESPACE_ID
  labels:
    name: backend
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    role: backend
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: backend
  namespace: NAMESPACE_ID
spec:
  selector:
    matchLabels:
      role: backend
  replicas: 2
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
      - name: ballot-backend
        image: b1f6c1c4/ballot-backend
        ports:
        - containerPort: 3000
      - name: mongos-container
        image: mongo
        command:
          - "mongos"
          - "--port"
          - "27017"
          - "--bind_ip"
          - "0.0.0.0"
          - "--configdb"
          - "NAMESPACE_ID-configsvr/mongodb-configdb-0.mongodb-configdb-headless-service.NAMESPACE_ID.svc.cluster.local:27019"
        ports:
          - containerPort: 27017
