apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: ballot-backend
        image: b1f6c1c4/ballot-backend
        ports:
        - containerPort: 3000


