FORMAT: 1A
HOST: https://b1f6c1c4-try-react.herokuapp.com/api

# Try React
A react boilerplate

# Group Default

## Check system status [GET /]
+ Response 200 (application/json; charset=utf-8)

    + Body

            {
              "version": "4907ca16",
              "commitHash": "4907ca16faf693b76a71df0efd19ef9dcefaa309"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "version": {
                  "type": "string"
                },
                "commitHash": {
                  "type": "string"
                }
              }
            }

# Group User

## Get credential [POST /login]
+ Request (application/json)

    + Body

            {
              "username": "admin",
              "password": "123456"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                }
              },
              "required": [
                "username",
                "password"
              ]
            }

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
              "message": "ok",
              "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNTEzOTMzNzQyLCJhdWQiOiJ0cnktcmVhY3QiLCJpc3MiOiJ0cnktcmVhY3QifQ.cp9bmi_jdVsetN4WcHYKdgOEtaMCZcHKDMy2_jTtkik"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "token": {
                  "type": "string"
                }
              }
            }

+ Response 401

## Get user profile [GET /profile]
+ Request
    + Headers

            Authorization: Bearer JWT

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
              "username": "admin"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string"
                }
              }
            }

+ Response 401
