// Actions
export const FETCH_STATUS_ACTION = 'StatusPage/FETCH_STATUS_ACTION';

// Sagas
export const CHECK_STATUS_REQUEST = 'StatusPage/CHECK_STATUS_REQUEST';
export const CHECK_STATUS_SUCCESS = 'StatusPage/CHECK_STATUS_SUCCESS';
export const CHECK_STATUS_FAILURE = 'StatusPage/CHECK_STATUS_FAILURE';
